tap "homebrew/bundle"
tap "homebrew/services", "https://mirrors.ustc.edu.cn/homebrew-services.git"

brew "aliyunpan"
brew "bash"
brew "binutils"
brew "coreutils"
brew "curl"
brew "findutils"
brew "fastfetch"
brew "go"
brew "hugo"
brew "httpie"
brew "jq"
brew "kubectl"
brew "kubectx"
brew "k9s"
brew "minikube"
brew "moreutils"
brew "nvm"
brew "rename"
brew "ssh-copy-id"
brew "tree"
brew "vim"
brew "wget"

cask "1password"
cask "baidunetdisk"
cask "feishu"
cask "google-chrome"
cask "insomnia"
cask "intellij-idea"
cask "orbstack"
cask "switchhosts"
cask "typora"
cask "ghostty"
cask "wechat"
